[tool.poetry]
name = "google-password-notifier"
version = "0.0.5"
description = ""
authors = ["Mikhail Tiurin <Mikhail Tiurin>"]
readme = "README.md"
packages = [{include = "google_password_notifier"}]

[tool.poetry.dependencies]
python = "^3.12.0"
google-api-python-client = "^2.155.0"
google-auth-oauthlib = "^1.2.1"
pyopenssl = "^24.3.0"
python-dateutil = "^2.9.0.post0"
pyyaml = "^6.0.2"
pathlib = "^1.0.1"
flake8 = "^7.1.1"

[tool.poetry.scripts]
google-password-notifier = "google_password_notifier.notify:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
